removed warning
stuvusIT/slapd-base pull request #18
Opened 2018-12-21 00:52 UTC by yccypuuck

there were two warnings in this role.
1. deprecated "with_items" for apt -> variables
2. usage of sudo command -> become

2018-12-21 12:48 UTC, SlothOfAnarchy requested changes

2018-12-21 12:48 UTC, SlothOfAnarchy commented on tasks/install.yml
> +    packages:
You can directly specify the list for the apt module, it is not necessary to use a variable for that:
```suggestion
- apt:
    name:
      - slapd
      - ldap-utils
      - schema2ldif
```

2018-12-27 21:23 UTC, yccypuuck commented on tasks/install.yml
> +    packages:
Thanks! fixed for both apt and pacman

2018-12-27 21:24 UTC, yccypuuck commented
PR updated with suggested changes

2018-12-27 21:25 UTC, SlothOfAnarchy approved these changes
:+1:

2018-12-27 21:25 UTC, merged